[package]
name = "golemdb-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
golemdb-cells.workspace = true
golemdb-index.workspace = true
golemdb-merkle.workspace = true
golemdb-storage.workspace = true
roaring.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
