[package]
name = "golemdb-integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dev-dependencies]
golemdb-api.workspace = true
golemdb-branch.workspace = true
golemdb-cells.workspace = true
golemdb-index.workspace = true
golemdb-merkle.workspace = true
golemdb-record.workspace = true
golemdb-storage.workspace = true
golemdb-storage-mdbx.workspace = true
proptest.workspace = true
criterion.workspace = true
tempfile = "3"

[[bench]]
name = "index"
harness = false
